services:
  # React app running on development mode
  weaponsforge-quartz-notes:
    container_name: weaponsforge-quartz-notes
    image: weaponsforge/quartz-notes:latest
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
